version: '3'
services:
        db:
                image: postgres
                environment:
                        - POSTGRES_DB=postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
        web:
                build: .
                ports:
                        - "8020:8020"
                environment:
                        - MIGRATE=true
                        - DJANGO_SUPERUSER_USERNAME=shashank
                        - POSTGRES_ENGINE=django.db.backends.postgresql_psycopg2
                        - POSTGRES_DB=postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                        - POSTGRES_HOST=db


